[tool.towncrier]
filename = "docs/changelog.md"
directory = "CHANGES/"
start_string = "# Changelog\n"
issue_format = "[#{issue}](https://gitlab.com/group/project/-/issues/{issue})"
underlines = ["", ""]
template = ".towncrier.md.jinja"
title_format = "## [{version}] - {project_date}"
